from os import eventfd_read
import argparse
import sys
import json
import os
import uuid
import urllib.request
import urllib.error
from pathlib import Path

#adding the backend to a sys.path so it doens't depend on the network
backend_path = Path(__file__).parent.parent / "1_Backend_Engine"
sys.path.append(str(backend_path.resolve()))

try:
    from checkov_parser import run_checkov_scan #type: ignore
    from risk_engine import calculate_risk #type: ignore
    from event_store import record_scan, init_db #type: ignore
except ImportError as e:
    print(f"FATAL: Could not load backend modules. Ensure 1_Backend_Engine exist alongside 2_CLI_Action. Error : {e}")
    sys.exit(1)

def run_scan(target: str, output_json: bool):
    ##Run the scan and logs it in DB
    init_db()

    target_path = Path(target).resolve()
    if not target_path.exists():
        print(f"Error: Target Path '{target}' does not exist.")
        sys.exit(1)
    
    if not output_json:
        print(f"--- Vanguard CLI : Scanning {target_path} ---")
    
    try:
        #parshing ASt
        raw_findings = run_checkov_scan(str(target_path))
        risk_data = calculate_risk(raw_findings)

        #filter the backup files from final result
        risk_data["files"] = [f for f in risk_data["files"] if not f.get("file_path", "").endswith(".vanguard_backup")]
        
        #log the event in the DB
        scan_id = f"clu_{uuid.uuid4(). hex[:8]}"
        record_scan(scan_id, "cli", str(target_path), risk_data["R_global"], risk_data["files"])

        #Output Results
        if output_json:
            #machineredable output for GitHub Actions / CI
            print(json.dumps({"scan_id": scan_id, "data": risk_data}, indent=2))
        else:
            #human readable output
            print(f"\n[+] Scan Complete. ID: {scan_id}")
            print(f"[+] Global Risk Score (R_global): {risk_data['R_global']:.2f}")
            print(f"[+] Files Processed: {len(risk_data['files'])}")
            print("-" * 50)

            for f in risk_data['files']:
                file_name = f.get('file_path') or f.get('file', 'Unknown File')
                print(f"  > {file_name} | R_file: {f['R_file']:.2f} | Findings: {len(f['findings'])}")
                
    except Exception as e:
        print(f"Error during scan execution: {e}")
        sys.exit(1)

def post_pr_comment(results_path: str):
    ##Formats scan JSOn into a Markdown and post it to GitHub PR via Rest Api
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    event_path = os.environ.get("GITHUB_EVENT_PATH")

    if not token or not repo or not event_path:
        print("Error: Missing required environement vriables (GITHUB_TOKEN, GITHUB_REPOSITORY, GITHUB_EVENT_PATH)")
        sys.exit(1)
    #Extracting PR number from the payload

    try:
        with open(event_path, "r") as f:
            event_data = json.load(f)
            pr_number = event_data.get("pull_request", {}).get("number")
    except Exception as e:
        print(f"Error reading GITHUB_EVENT_PATH: {e}")
        sys.exit(1)
    
    if not pr_number:
        print("Not a pull request event. Skipping comment posting.")
        return
    
    #Read scan results JSON
    with open(results_path, "r") as f:
        scan_payload = json.load(f)
    
    data = scan_payload.get("data", {})
    r_global = data.get("R_global", 0.0)
    files = data.get("files", [])

    #format markdown comment
    comment_body = f"## 🛡️ Vanguard Security Report \n\n"
    comment_body += f"**Global Risk Score ($R_{{global}}):** `{r_global:.2f}`\n\n"
    comment_body += "| File Path | Risk Score ($R_{{file}} | Findings Count |\n"
    comment_body += "| --- | --- | --- | \n"

    for file_info in files:
        path = file_info.get('file', 'Unknown File')
        r_file = file_info.get('R_file', 0.0)
        findings_count = len(file_info.get('findings', []))
        comment_body += f"| `{path}` | `{r_file:.2f}` | {findings_count} |\n"
    
    comment_body += "\n*Generated By VanguardNode 3D Automated CI Scanner*"
    

def main():
    parser = argparse.ArgumentParser(description="VanguardNode CLI - Zero-Trust DecSecOps Scanner")
    subparsers = parser.add_subparsers(dest="command", required=True)

    # scan command
    scan_parser = subparsers.add_parser("scan", help="Run a full scan on a target directory")
    scan_parser.add_argument("path", help="Target directory to scan")
    scan_parser.add_argument("--json", action="store_true", help="Output machine-readable JSON for CI integration")

    # comment-pr command
    pr_parser = subparsers.add_parser("comment-pr", help="Post findings as a GitHub PR comment")
    pr_parser.add_argument("--results", required=True, help="Path to the JSON results file from a previous scan")

    args = parser.parse_args()
    
    if args.command == "scan":
        run_scan(args.path, args.json)
    elif args.command == "comment-pr":
        print("GitHub PR Integration Module coming soon...")


if __name__ == "__main__":
    main()