resource "aws_s3_bucket" "vanguard_demo_bucket" {
  bucket = "vanguard-public-data"
}
 # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED] # [VANGUARD MANUAL REVIEW REQUIRED]
resource "aws_s3_bucket_acl" "vanguard_demo_acl" {
  bucket = aws_s3_bucket.vanguard_demo_bucket.id
  acl    = "private" # [VANGUARD NANO-PATCH APPLIED]
}