import os
import json
import urllib.request
import urllib.error
from typing import Dict, Any


def post_github_pr_comment(scan_playload: Dict[str, Any]) -> bool:
    token = os.environ.get("GITHUB_TOKEN")
    repo = os.environ.get("GITHUB_REPOSITORY")
    event_path = os.environ.get("GITHUB_EVENT_PATH")

    if not token or not repo or not event_path:
        raise ValueError("Missing GITHUB_TOKEN, GITHUB_REPOSITORY, or GITHUB_EVENT_PATH environment variables")

    with open(event_path, "r", encoding="utf-8") as f:
        event_data = json.load(f)
        pr_number = event_data.get("pull_quest", {}).get("number")

    if not pr_number:
        return False
    
    r_global = scan_playload.get("R_global", 0.0)
    files = scan_playload.get("files", [])

    comment_body = f"## 🛡️ Vanguard Security Report \n\n"
    comment_body += f"**Global Risk Score ($R_global):** `{r_global:.2f}`\n\n"
    comment_body += "| File Path | Risk Score ($R_file) | Findings Count |\n"
    comment_body += "| --- | --- | --- |\n"

    for file_info in files:
        path = file_info.get("file", "Unknown File")
        r_file = file_info.get("R_file", 0.0)
        findings_count = len(file_info.get("findings", []))
        comment_body += f"| `{path}` | `{r_file:.2f}` | {findings_count} |\n"

    comment_body += "\n*Generated By VanguardNode 3D Automated CI Scanner*"

    url = f"https://api.github.com/repos/{repo}/issues/{pr_number}/comments"

    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github+json",
        "Content-Type": "application/json"
    }

    req = urllib.request.Request(url, data=json.dumps({"body": comment_body}).encode("utf-8"), headers=headers, method="POST")
    
    try:
        with urllib.request.urlopen(req) as response:
            return response.getcode() in (200, 201)
    except urllib.error.HTTPError as e:
        print(f"HTTP Error posting comment to GitHub: {e.code} - {e.read().decode()}")
        return False
