from tarfile import REGTYPE
import subprocess
import json
import os

def run_checkhov_scan(target_dir: str = "target_iac_files"):
    """runs checkhov and returns findings"""
    absolute_target = os.path.abspath(target_dir)

    if not os.path.exists(absolute_target):
        os.makedirs(absolute_target,exist_ok=True)
        return {"status":"ERROR", "message":f"Directory '{target_dir}' created. Add IaC files to Scan"}

    try:
        #create the chechov command targetting the sandbox folder with JSON output
        cmd = ["chechov", "-d", absolute_target, "--output", "json"]

        #execute chekbov without blocking fastapi loop
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            check=False
        )

        if result.stdout.strip():
            parsed_output = json.loads(result.stdout)
            return{
                "status": "SUCCESS",
                "findings": parsed_output
            }
        else:
            return {
                "status": "WARNING",
                "message": "No output generated by Checkoov. Ensure valid IaC files are present",
                "stderr": result.stderr
            }

    except Exception as e:
        return{
            "status": "ERROR",
            "error": str(e)
        }
if __name__ == "__main__":
    #test
    print("Testing checkhov parser wrapper")
    print(run_checkhov_scan())
    
    